/* ==========================================================================
   app.js — boot, tab switching, theme toggle, cross-view navigation,
   and the Methods view (static prose driven by corpus metadata).
   ========================================================================== */
'use strict';

(async function () {

  const views = {
    map: () => MapView.activate(),
    trends: () => TrendsView.activate(),
    clusters: () => ClusterView.activate(),
    compare: () => CompareView.activate(),
    methods: () => {},
  };

  function switchView(name) {
    document.querySelectorAll('.tab').forEach(t =>
      t.classList.toggle('active', t.dataset.view === name));
    document.querySelectorAll('.view').forEach(v =>
      v.classList.toggle('active', v.id === 'view-' + name));
    (views[name] || views.map)();
  }

  document.querySelectorAll('.tab').forEach(t =>
    t.addEventListener('click', () => switchView(t.dataset.view)));

  ACC.on('switch-view', switchView);
  ACC.on('open-cluster', cid => { switchView('clusters'); ClusterView.open(cid); });

  /* --------------------------- methods view ----------------------------- */
  const PIPE = [
    { n: '01 · EXTRACT', t: 'Claims from abstracts', d: 'An LLM decomposes each abstract into atomic contribution claims — before any statistical analysis. Quality is human-validated (94.5% agreement with a 3-annotator majority, κ = 0.86).' },
    { n: '02 · EMBED', t: 'SPECTER2 vectors', d: 'Each claim is embedded with SPECTER2, a scientific-document encoder, capturing what is being claimed rather than surface wording.' },
    { n: '03 · CLUSTER', t: 'UMAP + HDBSCAN, jointly', d: 'All years are clustered together so a cluster means the same thing early and late in the period. Cluster labels are generated by an LLM from each cluster\'s representative claims.' },
    { n: '04 · AGGREGATE', t: 'Document frequency', d: 'Per cluster and year: the share of papers contributing at least one claim. Drift is the change of this share over time.' },
  ];

  function renderMethods(m) {
    const years = m.years;
    const y0 = years[0], y1 = years.at(-1);
    const noisePct = (m.noiseShare * 100).toFixed(0) + '%';
    const reviewedN = ACC.state.data.clusters.filter(c => c.reviewed).length;
    const labelNote = reviewedN
      ? `all ${reviewedN} clusters carry LLM-generated labels; each cluster's raw c-TF-IDF descriptors are shown alongside as key terms`
      : 'labels are raw c-TF-IDF descriptors';
    // The "of total" column only renders when the full-corpus counts are known.
    const hasTot = !!m.totalPapersPerYear;
    const rowStyle = hasTot ? '' : ' style="grid-template-columns:1fr 1fr 1fr"';
    const corpusRows = years.map((y, i) =>
      `<div class="corpus-row"${rowStyle}><span>${y}</span>` +
      `<span>${m.papersPerYear[i].toLocaleString()}</span>` +
      (hasTot ? `<span class="dim">of ${m.totalPapersPerYear[i].toLocaleString()}</span>` : '') +
      `<span>${m.claimsPerYear[i].toLocaleString()}</span></div>`).join('');

    // Auto-generated source statistics (venue · role · years · papers · claims).
    const sources = ACC.state.data.sources || [];
    const srcRows = sources.map(s => {
      const yr = (s.years && s.years.length)
        ? `${s.years[0]}–${s.years[s.years.length - 1]}` : '—';
      return `<div class="srcs-row"><span><span class="src-dot" style="background:${s.color}"></span>` +
        `${ACC.escapeHtml(s.venue)}</span>` +
        `<span>${s.role === 'clustered' ? 'reference corpus' : 'subsample'}</span>` +
        `<span>${yr}</span><span>${(s.nPapers || 0).toLocaleString()}</span>` +
        `<span>${(s.nClaims || 0).toLocaleString()}</span></div>`;
    }).join('');
    // Totals count the clustered corpus only — overlay sources are listed
    // above but named separately (they overlap the base and would double count).
    const clustered = sources.filter(s => s.role === 'clustered');
    const overlaid = sources.filter(s => s.role === 'overlay');
    const srcTotPapers = clustered.reduce((a, s) => a + (s.nPapers || 0), 0).toLocaleString();
    const srcTotClaims = clustered.reduce((a, s) => a + (s.nClaims || 0), 0).toLocaleString();
    const srcTotNote = overlaid.length
      ? ` (+ ${overlaid.reduce((a, s) => a + (s.nClaims || 0), 0).toLocaleString()} ${overlaid.map(s => s.venue).join('/')})` : '';

    // Consolidated how-to-read block for the extra layer (e.g. the AIRI
    // build) — every caveat in one place instead of scattered notes.
    let overlayBox = '';
    if (overlaid.length) {
      const o = overlaid[0];
      const oIdx = sources.findIndex(s => s.id === o.id);
      const P = ACC.state.data.points;
      let oN = 0, oNoise = 0;
      const oPapers = new Set(), basePapers = new Set();
      for (let i = 0; i < P.cluster.length; i++) {
        if (P.source[i] === oIdx) {
          oN++; if (P.cluster[i] === -1) oNoise++;
          oPapers.add(P.paper[i]);
        } else {
          basePapers.add(P.paper[i]);
        }
      }
      const oNoisePct = oN ? (100 * oNoise / oN).toFixed(0) + '%' : '—';
      let nOverlap = 0;
      for (const pid of oPapers) if (basePapers.has(pid)) nOverlap++;
      overlayBox = `
      <div class="methods-section">
        <h2 class="methods-h2">The ${ACC.escapeHtml(o.venue)} subsample</h2>
        <p class="methods-p">The ${ACC.escapeHtml(o.venue)} subsample (${(o.nPapers || 0).toLocaleString()} papers · ${(o.nClaims || 0).toLocaleString()} claims) is clustered jointly with the reference corpus: a single UMAP + HDBSCAN run assigns every claim its topic and map position. ${oNoisePct} of its claims remain unclustered, against ${noisePct} in the reference corpus.</p>
        <p class="methods-p">Reference statistics — trends, cluster sizes, document-frequency drift — count the six venues only. ${ACC.escapeHtml(o.venue)}'s presence in a topic is shown in Compare, in the map legend (◆), and in each cluster's source chips. Compare shares are computed over clustered claims and papers for all selections alike.</p>
        <p class="methods-p">The subsample spans every track its papers appeared in — main proceedings, Findings, demos, industry, the Student Research Workshop (SRW), tutorials and co-located events — whereas the reference corpus covers only the six conferences' own proceedings (long/short/main, demo, industry, SRW, tutorials) and excludes Findings and workshops. Track composition therefore contributes to profile differences.</p>
        <p class="methods-p">${nOverlap} ${ACC.escapeHtml(o.venue)} papers are also part of the reference corpus. Their claims enter the clustering once, and claim lists and author statistics count them once.</p>
      </div>`;
    }

    document.getElementById('methods-body').innerHTML = `
      <div class="methods-section" style="gap:10px">
        <div class="methods-eyebrow">METHODS</div>
        <h1 class="methods-h1">Measuring scientific drift, one claim at a time</h1>
        <p class="methods-lead">Drift Inspector quantifies how a research field moves by tracking <b>Atomic Contribution Claims (ACCs)</b> — self-contained, contribution-bearing propositions extracted from paper abstracts — rather than keywords or whole papers. Claims are clustered jointly across all ${years.length} years of the corpus (${y0}–${y1}), and each cluster's <i>document frequency</i> (the share of papers contributing at least one claim to it) is followed over time.</p>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Pipeline</h2>
        <div class="pipe-grid">
          ${PIPE.map(s => `<div class="pipe-card"><div class="pipe-n">${s.n}</div><div class="pipe-t">${s.t}</div><div class="pipe-d">${s.d}</div></div>`).join('')}
        </div>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Sources</h2>
        <p class="methods-p">All sources are embedded and clustered together in one run, so they share a single topic space and can be compared directly. The six conferences form the <b>reference corpus</b> that defines the statistics below; the AIRI subsample is clustered alongside them but not counted in those statistics. Any source can be shown, hidden, or highlighted from the map's <i>Sources</i> menu.</p>
        <div class="corpus-table">
          <div class="srcs-row head"><span>SOURCE</span><span>ROLE</span><span>YEARS</span><span>PAPERS</span><span>CLAIMS</span></div>
          ${srcRows}
          <div class="srcs-row total"><span>Total (reference corpus)</span><span></span><span></span><span>${srcTotPapers}</span><span>${srcTotClaims}${srcTotNote}</span></div>
        </div>
      </div>
      ${overlayBox}
      <div class="methods-section">
        <h2 class="methods-h2">Reference corpus by year</h2>
        <div class="corpus-table">
          <div class="corpus-row head"${rowStyle}><span>YEAR</span><span>PAPERS</span>${hasTot ? '<span>OF TOTAL</span>' : ''}<span>CLAIMS</span></div>
          ${corpusRows}
          <div class="corpus-note">Papers are a stratified (venue × year) random sample of the full main-conference corpus, drawn with a fixed seed for reproducibility; document-frequency shares divide by each year's sampled total, so they stay comparable across years. ${m.nClaims.toLocaleString()} claims in total; ${noisePct} remain unclustered — one-off contributions. ${m.nClusters} clusters; ${labelNote}.</div>
        </div>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Reading the views</h2>
        <p class="methods-p"><b class="serif">Map.</b> Every claim as a point in SPECTER2/UMAP space. Filter by year, recolor by drift trend — a relative scale built on the log-ratio of the ${y1} vs ${y0} share, so newly emerged or multi-fold-grown clusters read stronger than large clusters with modest growth (an ×8 change saturates the color). Search claims and titles, pin any point's card with a link to the source paper, isolate clusters from the legend (ctrl/cmd-click to combine).</p>
        <p class="methods-p"><b class="serif">Trends.</b> The ${y0} → ${y1} document-frequency shift as a butterfly chart, per-year trajectories for selected clusters (click bars or sparklines to add, capped at 12 lines for readability), and a sparkline overview of every cluster.</p>
        <p class="methods-p"><b class="serif">Clusters.</b> One cluster in depth: share of papers by year, its position in claim space, and all of its claims with links to the source papers — exportable as CSV.</p>
        <p class="methods-p"><b class="serif">Compare.</b> Two selections — a source (a venue or the AIRI subsample), an author, or a keyword set — side by side: each one's own topic profile, the gap between them, and how a selection drifts across years. Leave the second selection empty to study just one.</p>
        <p class="methods-p faint">A note on wording. Across the app, <b>share of papers</b> is a cluster's <i>document frequency</i> — the percentage of that year's sampled papers contributing at least one claim to the cluster — and <b>pp</b> (percentage points) is the change in that share from ${y0} to ${y1} (a move from 5% to 12% is +7&nbsp;pp). The drift colors and ▲/▼ arrows are driven by this measure; the “key terms” on the Clusters page are each cluster's raw c-TF-IDF descriptors; point positions come from the SPECTER2 / UMAP projection described above.</p>
      </div>

      <div class="methods-section">
        <h2 class="methods-h2">Validation &amp; release</h2>
        <p class="methods-p">The pipeline and its validation are described in the accompanying paper (under review). Extraction quality is human-validated (94.5% agreement with a 3-annotator majority, κ = 0.86); clustering is benchmarked against eight baselines on an external taxonomy and is robust across a 36-cell hyperparameter grid. The underlying ACL Anthology claim dataset is public (CC BY 4.0); this build is prepared for internal AIRI use.</p>
        <p class="methods-p faint">The tool is corpus-agnostic — the same interface can be rebuilt for any venue or field.</p>
        ${m.build ? `<p class="methods-p faint">Build ${ACC.escapeHtml(m.build.commit || '?')} · ${ACC.escapeHtml(m.build.date || '')}</p>` : ''}
      </div>`;
  }

  /* ------------------------------- boot --------------------------------- */
  ACC.initTheme();

  document.getElementById('theme-toggle').addEventListener('click', () => ACC.toggleTheme());
  ACC.on('theme', () => {
    MapView.rebuildTheme();
    TrendsView.rebuildTheme();
    ClusterView.rebuildTheme();
    CompareView.rebuildTheme();
  });

  // ⌘K / Ctrl-K focuses the map search.
  document.addEventListener('keydown', e => {
    if ((e.metaKey || e.ctrlKey) && (e.key === 'k' || e.key === 'K')) {
      e.preventDefault();
      switchView('map');
      setTimeout(() => { const s = document.getElementById('map-search'); if (s) s.focus(); }, 50);
    }
  });

  try {
    const data = await ACC.load();
    const m = data.meta;
    const totalPapers = m.papersPerYear.reduce((a, b) => a + b, 0);

    // Brand and per-corpus strings come from the data file, so swapping
    // data/acc_data.json relabels the whole app.
    document.getElementById('brand-title').textContent = m.title || 'Drift Inspector';
    document.getElementById('brand-sub').textContent = m.subtitle || '';
    document.title = (m.title || 'Drift Inspector') + (m.subtitle ? ' — ' + m.subtitle : '');
    document.getElementById('butterfly-title').textContent =
      `Topic-share shift ${m.years[0]} → ${m.years.at(-1)}`;
    document.getElementById('intro-year0').textContent = m.years[0];
    document.getElementById('corpus-meta').textContent =
      `${m.nClaims.toLocaleString()} claims · ${m.nClusters} clusters · ${totalPapers.toLocaleString()} papers`;
    document.getElementById('noise-pct').textContent = (m.noiseShare * 100).toFixed(0) + '%';
    document.getElementById('intro-count').textContent =
      `${m.nClaims.toLocaleString()} CLAIMS · ONE POINT EACH`;

    // Trend statistics are defined by the clustered corpus alone; on overlay
    // instances say so where the reader is looking.
    const overlaySrcs = (ACC.state.data.sources || []).filter(s => s.role === 'overlay');
    const scopeNote = document.getElementById('trends-scope-note');
    if (scopeNote && overlaySrcs.length) {
      const names = overlaySrcs.map(s => s.venue).join(', ');
      scopeNote.textContent =
        `Trend statistics cover the six reference venues. ${names} papers are not counted here; use Compare for the ${names} profile.`;
    }

    renderMethods(m);
    switchView('map');
  } catch (err) {
    document.querySelector('.app').innerHTML =
      `<div class="detail-empty" style="padding:40px;text-align:center">Failed to load data: ${ACC.escapeHtml(err.message)}<br>` +
      `The website build needs to be served over HTTP (data is fetched from <code>data/acc_data.json</code>). ` +
      `Use the portable single-file build to open locally.</div>`;
    throw err;
  }
})();
